/**
 * ISO 3166-1 alpha-2 country codes
 * Complete list of all countries
 */
export interface Country {
    code: string;
    name: string;
    nameFr: string;
}

export const COUNTRIES: Country[] = [
    { code: 'AF', name: 'Afghanistan', nameFr: 'Afghanistan' },
    { code: 'AX', name: 'Åland Islands', nameFr: 'Îles Åland' },
    { code: 'AL', name: 'Albania', nameFr: 'Albanie' },
    { code: 'DZ', name: 'Algeria', nameFr: 'Algérie' },
    { code: 'AS', name: 'American Samoa', nameFr: 'Samoa américaines' },
    { code: 'AD', name: 'Andorra', nameFr: 'Andorre' },
    { code: 'AO', name: 'Angola', nameFr: 'Angola' },
    { code: 'AI', name: 'Anguilla', nameFr: 'Anguilla' },
    { code: 'AQ', name: 'Antarctica', nameFr: 'Antarctique' },
    { code: 'AG', name: 'Antigua and Barbuda', nameFr: 'Antigua-et-Barbuda' },
    { code: 'AR', name: 'Argentina', nameFr: 'Argentine' },
    { code: 'AM', name: 'Armenia', nameFr: 'Arménie' },
    { code: 'AW', name: 'Aruba', nameFr: 'Aruba' },
    { code: 'AU', name: 'Australia', nameFr: 'Australie' },
    { code: 'AT', name: 'Austria', nameFr: 'Autriche' },
    { code: 'AZ', name: 'Azerbaijan', nameFr: 'Azerbaïdjan' },
    { code: 'BS', name: 'Bahamas', nameFr: 'Bahamas' },
    { code: 'BH', name: 'Bahrain', nameFr: 'Bahreïn' },
    { code: 'BD', name: 'Bangladesh', nameFr: 'Bangladesh' },
    { code: 'BB', name: 'Barbados', nameFr: 'Barbade' },
    { code: 'BY', name: 'Belarus', nameFr: 'Biélorussie' },
    { code: 'BE', name: 'Belgium', nameFr: 'Belgique' },
    { code: 'BZ', name: 'Belize', nameFr: 'Belize' },
    { code: 'BJ', name: 'Benin', nameFr: 'Bénin' },
    { code: 'BM', name: 'Bermuda', nameFr: 'Bermudes' },
    { code: 'BT', name: 'Bhutan', nameFr: 'Bhoutan' },
    { code: 'BO', name: 'Bolivia', nameFr: 'Bolivie' },
    { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', nameFr: 'Bonaire, Saint-Eustache et Saba' },
    { code: 'BA', name: 'Bosnia and Herzegovina', nameFr: 'Bosnie-Herzégovine' },
    { code: 'BW', name: 'Botswana', nameFr: 'Botswana' },
    { code: 'BV', name: 'Bouvet Island', nameFr: 'Île Bouvet' },
    { code: 'BR', name: 'Brazil', nameFr: 'Brésil' },
    { code: 'IO', name: 'British Indian Ocean Territory', nameFr: "Territoire britannique de l'océan Indien" },
    { code: 'BN', name: 'Brunei Darussalam', nameFr: 'Brunei' },
    { code: 'BG', name: 'Bulgaria', nameFr: 'Bulgarie' },
    { code: 'BF', name: 'Burkina Faso', nameFr: 'Burkina Faso' },
    { code: 'BI', name: 'Burundi', nameFr: 'Burundi' },
    { code: 'CV', name: 'Cabo Verde', nameFr: 'Cap-Vert' },
    { code: 'KH', name: 'Cambodia', nameFr: 'Cambodge' },
    { code: 'CM', name: 'Cameroon', nameFr: 'Cameroun' },
    { code: 'CA', name: 'Canada', nameFr: 'Canada' },
    { code: 'KY', name: 'Cayman Islands', nameFr: 'Îles Caïmans' },
    { code: 'CF', name: 'Central African Republic', nameFr: 'République centrafricaine' },
    { code: 'TD', name: 'Chad', nameFr: 'Tchad' },
    { code: 'CL', name: 'Chile', nameFr: 'Chili' },
    { code: 'CN', name: 'China', nameFr: 'Chine' },
    { code: 'CX', name: 'Christmas Island', nameFr: 'Île Christmas' },
    { code: 'CC', name: 'Cocos (Keeling) Islands', nameFr: 'Îles Cocos' },
    { code: 'CO', name: 'Colombia', nameFr: 'Colombie' },
    { code: 'KM', name: 'Comoros', nameFr: 'Comores' },
    { code: 'CG', name: 'Congo', nameFr: 'Congo' },
    { code: 'CD', name: 'Congo, Democratic Republic of the', nameFr: 'Congo (RDC)' },
    { code: 'CK', name: 'Cook Islands', nameFr: 'Îles Cook' },
    { code: 'CR', name: 'Costa Rica', nameFr: 'Costa Rica' },
    { code: 'CI', name: 'Côte d\'Ivoire', nameFr: 'Côte d\'Ivoire' },
    { code: 'HR', name: 'Croatia', nameFr: 'Croatie' },
    { code: 'CU', name: 'Cuba', nameFr: 'Cuba' },
    { code: 'CW', name: 'Curaçao', nameFr: 'Curaçao' },
    { code: 'CY', name: 'Cyprus', nameFr: 'Chypre' },
    { code: 'CZ', name: 'Czechia', nameFr: 'Tchéquie' },
    { code: 'DK', name: 'Denmark', nameFr: 'Danemark' },
    { code: 'DJ', name: 'Djibouti', nameFr: 'Djibouti' },
    { code: 'DM', name: 'Dominica', nameFr: 'Dominique' },
    { code: 'DO', name: 'Dominican Republic', nameFr: 'République dominicaine' },
    { code: 'EC', name: 'Ecuador', nameFr: 'Équateur' },
    { code: 'EG', name: 'Egypt', nameFr: 'Égypte' },
    { code: 'SV', name: 'El Salvador', nameFr: 'Salvador' },
    { code: 'GQ', name: 'Equatorial Guinea', nameFr: 'Guinée équatoriale' },
    { code: 'ER', name: 'Eritrea', nameFr: 'Érythrée' },
    { code: 'EE', name: 'Estonia', nameFr: 'Estonie' },
    { code: 'SZ', name: 'Eswatini', nameFr: 'Eswatini' },
    { code: 'ET', name: 'Ethiopia', nameFr: 'Éthiopie' },
    { code: 'FK', name: 'Falkland Islands', nameFr: 'Îles Malouines' },
    { code: 'FO', name: 'Faroe Islands', nameFr: 'Îles Féroé' },
    { code: 'FJ', name: 'Fiji', nameFr: 'Fidji' },
    { code: 'FI', name: 'Finland', nameFr: 'Finlande' },
    { code: 'FR', name: 'France', nameFr: 'France' },
    { code: 'GF', name: 'French Guiana', nameFr: 'Guyane française' },
    { code: 'PF', name: 'French Polynesia', nameFr: 'Polynésie française' },
    { code: 'TF', name: 'French Southern Territories', nameFr: 'Terres australes françaises' },
    { code: 'GA', name: 'Gabon', nameFr: 'Gabon' },
    { code: 'GM', name: 'Gambia', nameFr: 'Gambie' },
    { code: 'GE', name: 'Georgia', nameFr: 'Géorgie' },
    { code: 'DE', name: 'Germany', nameFr: 'Allemagne' },
    { code: 'GH', name: 'Ghana', nameFr: 'Ghana' },
    { code: 'GI', name: 'Gibraltar', nameFr: 'Gibraltar' },
    { code: 'GR', name: 'Greece', nameFr: 'Grèce' },
    { code: 'GL', name: 'Greenland', nameFr: 'Groenland' },
    { code: 'GD', name: 'Grenada', nameFr: 'Grenade' },
    { code: 'GP', name: 'Guadeloupe', nameFr: 'Guadeloupe' },
    { code: 'GU', name: 'Guam', nameFr: 'Guam' },
    { code: 'GT', name: 'Guatemala', nameFr: 'Guatemala' },
    { code: 'GG', name: 'Guernsey', nameFr: 'Guernesey' },
    { code: 'GN', name: 'Guinea', nameFr: 'Guinée' },
    { code: 'GW', name: 'Guinea-Bissau', nameFr: 'Guinée-Bissau' },
    { code: 'GY', name: 'Guyana', nameFr: 'Guyana' },
    { code: 'HT', name: 'Haiti', nameFr: 'Haïti' },
    { code: 'HM', name: 'Heard Island and McDonald Islands', nameFr: 'Îles Heard-et-MacDonald' },
    { code: 'VA', name: 'Holy See', nameFr: 'Saint-Siège (Vatican)' },
    { code: 'HN', name: 'Honduras', nameFr: 'Honduras' },
    { code: 'HK', name: 'Hong Kong', nameFr: 'Hong Kong' },
    { code: 'HU', name: 'Hungary', nameFr: 'Hongrie' },
    { code: 'IS', name: 'Iceland', nameFr: 'Islande' },
    { code: 'IN', name: 'India', nameFr: 'Inde' },
    { code: 'ID', name: 'Indonesia', nameFr: 'Indonésie' },
    { code: 'IR', name: 'Iran', nameFr: 'Iran' },
    { code: 'IQ', name: 'Iraq', nameFr: 'Irak' },
    { code: 'IE', name: 'Ireland', nameFr: 'Irlande' },
    { code: 'IM', name: 'Isle of Man', nameFr: 'Île de Man' },
    { code: 'IL', name: 'Israel', nameFr: 'Israël' },
    { code: 'IT', name: 'Italy', nameFr: 'Italie' },
    { code: 'JM', name: 'Jamaica', nameFr: 'Jamaïque' },
    { code: 'JP', name: 'Japan', nameFr: 'Japon' },
    { code: 'JE', name: 'Jersey', nameFr: 'Jersey' },
    { code: 'JO', name: 'Jordan', nameFr: 'Jordanie' },
    { code: 'KZ', name: 'Kazakhstan', nameFr: 'Kazakhstan' },
    { code: 'KE', name: 'Kenya', nameFr: 'Kenya' },
    { code: 'KI', name: 'Kiribati', nameFr: 'Kiribati' },
    { code: 'KP', name: 'Korea (North)', nameFr: 'Corée du Nord' },
    { code: 'KR', name: 'Korea (South)', nameFr: 'Corée du Sud' },
    { code: 'KW', name: 'Kuwait', nameFr: 'Koweït' },
    { code: 'KG', name: 'Kyrgyzstan', nameFr: 'Kirghizistan' },
    { code: 'LA', name: 'Lao People\'s Democratic Republic', nameFr: 'Laos' },
    { code: 'LV', name: 'Latvia', nameFr: 'Lettonie' },
    { code: 'LB', name: 'Lebanon', nameFr: 'Liban' },
    { code: 'LS', name: 'Lesotho', nameFr: 'Lesotho' },
    { code: 'LR', name: 'Liberia', nameFr: 'Libéria' },
    { code: 'LY', name: 'Libya', nameFr: 'Libye' },
    { code: 'LI', name: 'Liechtenstein', nameFr: 'Liechtenstein' },
    { code: 'LT', name: 'Lithuania', nameFr: 'Lituanie' },
    { code: 'LU', name: 'Luxembourg', nameFr: 'Luxembourg' },
    { code: 'MO', name: 'Macao', nameFr: 'Macao' },
    { code: 'MG', name: 'Madagascar', nameFr: 'Madagascar' },
    { code: 'MW', name: 'Malawi', nameFr: 'Malawi' },
    { code: 'MY', name: 'Malaysia', nameFr: 'Malaisie' },
    { code: 'MV', name: 'Maldives', nameFr: 'Maldives' },
    { code: 'ML', name: 'Mali', nameFr: 'Mali' },
    { code: 'MT', name: 'Malta', nameFr: 'Malte' },
    { code: 'MH', name: 'Marshall Islands', nameFr: 'Îles Marshall' },
    { code: 'MQ', name: 'Martinique', nameFr: 'Martinique' },
    { code: 'MR', name: 'Mauritania', nameFr: 'Mauritanie' },
    { code: 'MU', name: 'Mauritius', nameFr: 'Maurice' },
    { code: 'YT', name: 'Mayotte', nameFr: 'Mayotte' },
    { code: 'MX', name: 'Mexico', nameFr: 'Mexique' },
    { code: 'FM', name: 'Micronesia', nameFr: 'Micronésie' },
    { code: 'MD', name: 'Moldova', nameFr: 'Moldavie' },
    { code: 'MC', name: 'Monaco', nameFr: 'Monaco' },
    { code: 'MN', name: 'Mongolia', nameFr: 'Mongolie' },
    { code: 'ME', name: 'Montenegro', nameFr: 'Monténégro' },
    { code: 'MS', name: 'Montserrat', nameFr: 'Montserrat' },
    { code: 'MA', name: 'Morocco', nameFr: 'Maroc' },
    { code: 'MZ', name: 'Mozambique', nameFr: 'Mozambique' },
    { code: 'MM', name: 'Myanmar', nameFr: 'Myanmar' },
    { code: 'NA', name: 'Namibia', nameFr: 'Namibie' },
    { code: 'NR', name: 'Nauru', nameFr: 'Nauru' },
    { code: 'NP', name: 'Nepal', nameFr: 'Népal' },
    { code: 'NL', name: 'Netherlands', nameFr: 'Pays-Bas' },
    { code: 'NC', name: 'New Caledonia', nameFr: 'Nouvelle-Calédonie' },
    { code: 'NZ', name: 'New Zealand', nameFr: 'Nouvelle-Zélande' },
    { code: 'NI', name: 'Nicaragua', nameFr: 'Nicaragua' },
    { code: 'NE', name: 'Niger', nameFr: 'Niger' },
    { code: 'NG', name: 'Nigeria', nameFr: 'Nigeria' },
    { code: 'NU', name: 'Niue', nameFr: 'Niue' },
    { code: 'NF', name: 'Norfolk Island', nameFr: 'Île Norfolk' },
    { code: 'MK', name: 'North Macedonia', nameFr: 'Macédoine du Nord' },
    { code: 'MP', name: 'Northern Mariana Islands', nameFr: 'Îles Mariannes du Nord' },
    { code: 'NO', name: 'Norway', nameFr: 'Norvège' },
    { code: 'OM', name: 'Oman', nameFr: 'Oman' },
    { code: 'PK', name: 'Pakistan', nameFr: 'Pakistan' },
    { code: 'PW', name: 'Palau', nameFr: 'Palaos' },
    { code: 'PS', name: 'Palestine, State of', nameFr: 'Palestine' },
    { code: 'PA', name: 'Panama', nameFr: 'Panama' },
    { code: 'PG', name: 'Papua New Guinea', nameFr: 'Papouasie-Nouvelle-Guinée' },
    { code: 'PY', name: 'Paraguay', nameFr: 'Paraguay' },
    { code: 'PE', name: 'Peru', nameFr: 'Pérou' },
    { code: 'PH', name: 'Philippines', nameFr: 'Philippines' },
    { code: 'PN', name: 'Pitcairn', nameFr: 'Îles Pitcairn' },
    { code: 'PL', name: 'Poland', nameFr: 'Pologne' },
    { code: 'PT', name: 'Portugal', nameFr: 'Portugal' },
    { code: 'PR', name: 'Puerto Rico', nameFr: 'Porto Rico' },
    { code: 'QA', name: 'Qatar', nameFr: 'Qatar' },
    { code: 'RE', name: 'Réunion', nameFr: 'La Réunion' },
    { code: 'RO', name: 'Romania', nameFr: 'Roumanie' },
    { code: 'RU', name: 'Russian Federation', nameFr: 'Russie' },
    { code: 'RW', name: 'Rwanda', nameFr: 'Rwanda' },
    { code: 'BL', name: 'Saint Barthélemy', nameFr: 'Saint-Barthélemy' },
    { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', nameFr: 'Sainte-Hélène, Ascension et Tristan da Cunha' },
    { code: 'KN', name: 'Saint Kitts and Nevis', nameFr: 'Saint-Kitts-et-Nevis' },
    { code: 'LC', name: 'Saint Lucia', nameFr: 'Sainte-Lucie' },
    { code: 'MF', name: 'Saint Martin', nameFr: 'Saint-Martin' },
    { code: 'PM', name: 'Saint Pierre and Miquelon', nameFr: 'Saint-Pierre-et-Miquelon' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', nameFr: 'Saint-Vincent-et-les-Grenadines' },
    { code: 'WS', name: 'Samoa', nameFr: 'Samoa' },
    { code: 'SM', name: 'San Marino', nameFr: 'Saint-Marin' },
    { code: 'ST', name: 'Sao Tome and Principe', nameFr: 'Sao Tomé-et-Principe' },
    { code: 'SA', name: 'Saudi Arabia', nameFr: 'Arabie saoudite' },
    { code: 'SN', name: 'Senegal', nameFr: 'Sénégal' },
    { code: 'RS', name: 'Serbia', nameFr: 'Serbie' },
    { code: 'SC', name: 'Seychelles', nameFr: 'Seychelles' },
    { code: 'SL', name: 'Sierra Leone', nameFr: 'Sierra Leone' },
    { code: 'SG', name: 'Singapore', nameFr: 'Singapour' },
    { code: 'SX', name: 'Sint Maarten', nameFr: 'Saint-Martin (partie néerlandaise)' },
    { code: 'SK', name: 'Slovakia', nameFr: 'Slovaquie' },
    { code: 'SI', name: 'Slovenia', nameFr: 'Slovénie' },
    { code: 'SB', name: 'Solomon Islands', nameFr: 'Îles Salomon' },
    { code: 'SO', name: 'Somalia', nameFr: 'Somalie' },
    { code: 'ZA', name: 'South Africa', nameFr: 'Afrique du Sud' },
    { code: 'GS', name: 'South Georgia and the South Sandwich Islands', nameFr: 'Géorgie du Sud-et-les Îles Sandwich du Sud' },
    { code: 'SS', name: 'South Sudan', nameFr: 'Soudan du Sud' },
    { code: 'ES', name: 'Spain', nameFr: 'Espagne' },
    { code: 'LK', name: 'Sri Lanka', nameFr: 'Sri Lanka' },
    { code: 'SD', name: 'Sudan', nameFr: 'Soudan' },
    { code: 'SR', name: 'Suriname', nameFr: 'Suriname' },
    { code: 'SJ', name: 'Svalbard and Jan Mayen', nameFr: 'Svalbard et Jan Mayen' },
    { code: 'SE', name: 'Sweden', nameFr: 'Suède' },
    { code: 'CH', name: 'Switzerland', nameFr: 'Suisse' },
    { code: 'SY', name: 'Syrian Arab Republic', nameFr: 'Syrie' },
    { code: 'TW', name: 'Taiwan', nameFr: 'Taïwan' },
    { code: 'TJ', name: 'Tajikistan', nameFr: 'Tadjikistan' },
    { code: 'TZ', name: 'Tanzania', nameFr: 'Tanzanie' },
    { code: 'TH', name: 'Thailand', nameFr: 'Thaïlande' },
    { code: 'TL', name: 'Timor-Leste', nameFr: 'Timor oriental' },
    { code: 'TG', name: 'Togo', nameFr: 'Togo' },
    { code: 'TK', name: 'Tokelau', nameFr: 'Tokelau' },
    { code: 'TO', name: 'Tonga', nameFr: 'Tonga' },
    { code: 'TT', name: 'Trinidad and Tobago', nameFr: 'Trinité-et-Tobago' },
    { code: 'TN', name: 'Tunisia', nameFr: 'Tunisie' },
    { code: 'TR', name: 'Turkey', nameFr: 'Turquie' },
    { code: 'TM', name: 'Turkmenistan', nameFr: 'Turkménistan' },
    { code: 'TC', name: 'Turks and Caicos Islands', nameFr: 'Îles Turques-et-Caïques' },
    { code: 'TV', name: 'Tuvalu', nameFr: 'Tuvalu' },
    { code: 'UG', name: 'Uganda', nameFr: 'Ouganda' },
    { code: 'UA', name: 'Ukraine', nameFr: 'Ukraine' },
    { code: 'AE', name: 'United Arab Emirates', nameFr: 'Émirats arabes unis' },
    { code: 'GB', name: 'United Kingdom', nameFr: 'Royaume-Uni' },
    { code: 'UM', name: 'United States Minor Outlying Islands', nameFr: 'Îles mineures éloignées des États-Unis' },
    { code: 'US', name: 'United States of America', nameFr: 'États-Unis' },
    { code: 'UY', name: 'Uruguay', nameFr: 'Uruguay' },
    { code: 'UZ', name: 'Uzbekistan', nameFr: 'Ouzbékistan' },
    { code: 'VU', name: 'Vanuatu', nameFr: 'Vanuatu' },
    { code: 'VE', name: 'Venezuela', nameFr: 'Venezuela' },
    { code: 'VN', name: 'Viet Nam', nameFr: 'Viêt Nam' },
    { code: 'VG', name: 'Virgin Islands (British)', nameFr: 'Îles Vierges britanniques' },
    { code: 'VI', name: 'Virgin Islands (U.S.)', nameFr: 'Îles Vierges des États-Unis' },
    { code: 'WF', name: 'Wallis and Futuna', nameFr: 'Wallis-et-Futuna' },
    { code: 'EH', name: 'Western Sahara', nameFr: 'Sahara occidental' },
    { code: 'YE', name: 'Yemen', nameFr: 'Yémen' },
    { code: 'ZM', name: 'Zambia', nameFr: 'Zambie' },
    { code: 'ZW', name: 'Zimbabwe', nameFr: 'Zimbabwe' }
];

/**
 * Get country name by code
 * @param code ISO 3166-1 alpha-2 country code
 * @param language Language for the name (default: 'fr')
 * @returns Country name or code if not found
 */
export const getCountryName = (code: string, language: 'fr' | 'en' = 'fr'): string => {
    if (!code) return '';
    const country = COUNTRIES.find(c => c.code === code);
    if (!country) return code;
    return language === 'fr' ? country.nameFr : country.name;
};

/**
 * Get country code by name
 * @param name Country name (in French or English)
 * @returns ISO 3166-1 alpha-2 country code or empty string if not found
 */
export const getCountryCode = (name: string): string => {
    if (!name) return '';
    const country = COUNTRIES.find(
        c => c.nameFr.toLowerCase() === name.toLowerCase() ||
             c.name.toLowerCase() === name.toLowerCase()
    );
    return country?.code || '';
};
